class Exce{
	 public static void main(String[] args) {
	try {
int a=1,b=2,c;
c=a+b;
System.exit(0);
System.out.println(c);

    return ;
}
catch (Exception ex) {
    
   
    return ;
}
finally {
    System.out.println("Inside finally");
}
}
}